### ISSUE TITLE
Include the database

### ISSUE THREAD

**Issue by tahirsada** [mamprogr/Quran-Resources#2]
السَّلآمُ عَلَيْكُمْ وَرَحْمَةُ الله وبَرَكآتُه
Please include the database dump or provide any alternative to the project.
  جزاك اللهُ خيراً

**Comment by mamprogr** [comment]
وعليكم السلام ورحمة الله وبركاته،

جميع المصادر وقواعد البيانات قمت بجلبها من هنا:
موقع تنزيل
http://tanzil.net/wiki/Resources
أرجو منكم في حال كنتم تعملون على مشروع مفتوح المصدر أن تبقيني عى اطلاع به أو إعطائي رابط مثلاً..

The resources database can be found here:
Tanzil Project
http://tanzil.net/wiki/Resources
Hope you if you were doing an open source project to keep me informed about it, for example, or give me a link ..

بالتوفيق :)
